@echo off
:lol
@echo DNA
@echo  DNA
@echo   DNA
@echo    DNA
@echo     DNA
@echo      DNA
@echo       DNA
@echo        DNA
@echo         DNA
@echo          DNA
@echo           DNA
@echo            DNA
@echo             DNA
@echo              DNA
@echo               DNA
@echo                DNA
@echo                 DNA
@echo                  DNA
@echo                   DNA
@echo                    DNA
@echo                     DNA
@echo                      DNA
@echo                       DNA
@echo                        DNA
@echo                         DNA
@echo                          DNA
@echo                           DNA
@echo                            DNA
@echo                             DNA
@echo                              DNA
@echo                               DNA
@echo                                DNA
@echo                                 DNA
@echo                                  DNA
@echo                                   DNA
@echo                                    DNA
@echo                                     DNA
@echo                                      DNA
@echo                                       DNA
@echo                                        DNA
@echo                                         DNA
@echo                                          DNA
@echo                                           DNA
@echo                                            DNA
@echo                                             DNA
@echo                                              DNA
@echo                                               DNA
@echo                                                DNA
@echo                                                 DNA
@echo                                                  DNA
@echo                                                   DNA
@echo                                                    DNA
@echo                                                     DNA
@echo                                                      DNA
@echo                                                       DNA
@echo                                                        DNA
@echo                                                         DNA
@echo                                                          DNA
@echo                                                           DNA
@echo                                                            DNA
@echo                                                             DNA
@echo                                                              DNA
@echo                                                               DNA
@echo                                                                DNA
@echo                                                                 DNA
@echo                                                                  DNA
@echo                                                                   DNA
@echo                                                                    DNA
@echo                                                                     DNA
@echo                                                                      DNA
@echo                                                                       DNA
@echo                                                                        DNA
@echo                                                                         DNA
@echo                                                                          DNA
@echo                                                                           DNA
@echo                                                                            DNA
@echo                                                                             DNA
@echo                                                                              DNA
@echo                                                                               DNA
@echo                                                                                DNA
@echo                                                                                 DNA
@echo                                                                                  DNA
@echo                                                                                   DNA
@echo                                                                                    DNA
@echo                                                                                     DNA
@echo                                                                                      DNA
@echo                                                                                       DNA
@echo                                                                                        DNA
@echo                                                                                         DNA
@echo                                                                                          DNA
@echo                                                                                           DNA
@echo                                                                                            DNA
@echo                                                                                             DNA
@echo                                                                                              DNA
@echo                                                                                               DNA
@echo                                                                                                DNA
@echo                                                                                                 DNA
@echo                                                                                                  DNA
@echo                                                                                                   DNA
@echo                                                                                                    DNA
@echo                                                                                                     DNA
@echo                                                                                                      DNA
@echo                                                                                                       DNA
@echo                                                                                                        DNA
@echo                                                                                                         DNA
@echo                                                                                                          DNA
@echo                                                                                                           DNA
@echo                                                                                                            DNA
@echo                                                                                                             DNA
@echo                                                                                                              DNA
@echo                                                                                                               DNA
@echo                                                                                                                DNA
@echo                                                                                                                 DNA
@echo                                                                                                                  DNA
@echo                                                                                                                   DNA
@echo                                                                                                                    DNA
@echo                                                                                                                     DNA
@echo                                                                                                                      DNA
@echo                                                                                                                     DNA
@echo                                                                                                                    DNA
@echo                                                                                                                   DNA
@echo                                                                                                                  DNA
@echo                                                                                                                 DNA
@echo                                                                                                                DNA
@echo                                                                                                               DNA
@echo                                                                                                              DNA
@echo                                                                                                             DNA
@echo                                                                                                            DNA
@echo                                                                                                           DNA
@echo                                                                                                          DNA
@echo                                                                                                         DNA
@echo                                                                                                        DNA
@echo                                                                                                       DNA
@echo                                                                                                      DNA
@echo                                                                                                     DNA
@echo                                                                                                    DNA
@echo                                                                                                   DNA
@echo                                                                                                  DNA
@echo                                                                                                 DNA
@echo                                                                                                DNA
@echo                                                                                               DNA
@echo                                                                                              DNA
@echo                                                                                             DNA
@echo                                                                                            DNA
@echo                                                                                           DNA
@echo                                                                                          DNA
@echo                                                                                         DNA
@echo                                                                                        DNA
@echo                                                                                       DNA
@echo                                                                                      DNA
@echo                                                                                     DNA
@echo                                                                                    DNA
@echo                                                                                   DNA
@echo                                                                                  DNA
@echo                                                                                 DNA
@echo                                                                                DNA
@echo                                                                               DNA
@echo                                                                              DNA
@echo                                                                             DNA
@echo                                                                            DNA
@echo                                                                           DNA
@echo                                                                          DNA
@echo                                                                         DNA
@echo                                                                        DNA
@echo                                                                       DNA
@echo                                                                      DNA
@echo                                                                     DNA
@echo                                                                    DNA
@echo                                                                   DNA
@echo                                                                  DNA
@echo                                                                 DNA
@echo                                                                DNA
@echo                                                               DNA
@echo                                                              DNA
@echo                                                             DNA
@echo                                                            DNA
@echo                                                           DNA
@echo                                                          DNA
@echo                                                         DNA
@echo                                                        DNA
@echo                                                       DNA
@echo                                                      DNA
@echo                                                     DNA
@echo                                                    DNA
@echo                                                   DNA
@echo                                                  DNA
@echo                                                 DNA
@echo                                                DNA
@echo                                               DNA
@echo                                              DNA
@echo                                             DNA
@echo                                            DNA
@echo                                           DNA
@echo                                          DNA
@echo                                         DNA
@echo                                        DNA
@echo                                       DNA
@echo                                      DNA
@echo                                     DNA
@echo                                    DNA
@echo                                   DNA
@echo                                  DNA
@echo                                 DNA
@echo                                DNA
@echo                               DNA
@echo                              DNA
@echo                             DNA
@echo                            DNA
@echo                           DNA
@echo                          DNA
@echo                         DNA
@echo                        DNA
@echo                       DNA
@echo                      DNA
@echo                     DNA
@echo                    DNA
@echo                   DNA
@echo                  DNA
@echo                 DNA
@echo                DNA
@echo               DNA
@echo              DNA
@echo             DNA
@echo            DNA
@echo           DNA
@echo          DNA
@echo         DNA
@echo        DNA
@echo       DNA
@echo      DNA
@echo     DNA
@echo    DNA
@echo   DNA
@echo  DNA
@echo DNA
goto lol